Multi_DB_Router/Multi_DB_Router/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from .views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='common-home'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^product/', include(('product.urls', 'users'), namespace='product')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Multi_DB_Router/product/urls.py
"""Users urls."""
from .views import ProductHomeView
from django.conf.urls import url

urlpatterns = [
    url(r'^product/$', ProductHomeView.as_view(), name='product'),
    url(r'^details/(?P<id>\d+)/(?P<data>[\w-]+)/$', ProductHomeView.as_view(), name='product_detail'),
]

Multi_DB_Router/users/urls.py
"""Users urls."""
from .views import LoginView, HomeView
from django.conf.urls import url


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^details/(?P<id>\d+)/$', HomeView.as_view(), name='user_detail'),
]

Multi_DB_Router/product/models.py
"""Product Model."""

from django.db import models

DATABASE = (
    ('data1_db', 'data1_db'),
    ('data2_db', 'data2_db'),
    ('data3_db', 'data3_db'),
    ('data4_db', 'data4_db'),
)


class ProductModel(models.Model):
    """Product model for details."""

    user = models.IntegerField(null=True, blank=True)
    product_name = models.CharField(max_length=255)
    product_description = models.TextField()
    database = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        """Meta Info."""

        app_label = 'product'
        verbose_name = 'ProductModel'
        verbose_name_plural = 'ProductModel'

    def __str__(self):
        """Return String."""
        return self.product_name

Multi_DB_Router/users/models.py
"""Model for the auth user creation."""
from django.db import models

from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from multiselectfield import MultiSelectField


DATABASE = (
    ('data1_db', 'data1_db'),
    ('data2_db', 'data2_db'),
    ('data3_db', 'data3_db'),
    ('data4_db', 'data4_db'),
)

""" git clone https://github.com/vishalpolley/django-multidb.git"""


class CustomUserManager(BaseUserManager):
    """Cutomer Manager BaseUserManager."""

    def create_user(self, email, password):
        """Create user."""
        if not email:
            raise ValueError("Users must register an email")

        user = self.model(email=CustomUserManager.normalize_email(email))
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """Create superuser."""
        user = self.create_user(email, password)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """Using email instead of username."""

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    is_staff = models.BooleanField(default=False)
    database = MultiSelectField(choices=DATABASE, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        """Meta Info."""

        app_label = 'users'
        verbose_name = 'CustomUser'
        verbose_name_plural = 'CustomUser'

    def __str__(self):
        """Str method to return ContactInfo name."""
        return self.email

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

Multi_DB_Router/product/forms.py
"""Forms for Product."""
from django import forms
from product.models import ProductModel, DATABASE


class ProductForm(forms.ModelForm):
    """Established Business for Sale form."""

    class Meta:
        """Definition for this class."""

        model = ProductModel
        fields = ['product_name', 'product_description', 'database']

    def __init__(self, *args, **kwargs):
        """Override fields objects."""
        self.request = kwargs.pop('request')
        super(ProductForm, self).__init__(*args, **kwargs)
        database = DATABASE if self.request.user.is_staff else ((data, data) for data in self.request.user.database)
        self.fields['database'].required = True
        self.fields['database'] = forms.ChoiceField(choices=database)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': self.fields[field].label
            })

Multi_DB_Router/users/forms.py
"""Forms for users."""
from .models import CustomUser
from django import forms
# from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.ModelForm):
    """Established Business for Sale form."""

    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

    class Meta:
        """Definition for this class."""

        model = CustomUser
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        """Override fields objects."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['password'].required = True
        self.fields['email'].required = True

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': self.fields[field].label
            })


class SignUpForm(forms.ModelForm):
    """Customer Form."""

    class Meta:
        """Meta Info."""

        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'password', 'database']

    def __init__(self, *args, **kwargs):
        """Override fields objects."""
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['password'].required = True
        self.fields['email'].required = True

        for field in iter(self.fields):
            if field != 'database':
                self.fields[field].widget.attrs.update({
                    'class': 'form-control',
                    'placeholder': self.fields[field].label
                })

Multi_DB_Router/product/views.py
"""Views for Products.."""
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from .models import ProductModel
from .forms import ProductForm


class ProductHomeView(LoginRequiredMixin, View):
    """Docstring for HomeView."""

    def get(self, request, *args, **kwargs):
        """To get Dashboard."""
        product_form = ProductForm(request=request)
        if kwargs.get('id'):
            product = ProductModel.objects.using(kwargs.get('data')).get(id=kwargs.get('id'))
            product_form = ProductForm(request=request, instance=product)
        product_sec = []
        databases = ['data1_db', 'data2_db', 'data3_db', 'data4_db'] if request.user.is_staff else request.user.database
        for database in databases:
            products_list = ProductModel.objects.using(database).filter(user=request.user.id)
            if request.user.is_staff:
                products_list = ProductModel.objects.using(database).all()
            for pro in products_list:
                product_sec.append((database, pro))
        return render(request, 'product.html', {"product": product_form, 'product_list': product_sec,
                      'id': kwargs.get('id'), 'data': kwargs.get('data')})

    def post(self, request, *args, **kwargs):
        """To save the product."""
        form = ProductForm(request.POST, request=request)
        if kwargs.get('id'):
            product = ProductModel.objects.using(kwargs.get('data')).get(id=kwargs.get('id'))
            form = ProductForm(request.POST, request=request, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user.id
            database = kwargs.get('data') if kwargs.get('data') else request.POST.get('database')
            product.save(using=database)
            messages.success(request, 'Product has been successfully added')
        return redirect('product:product')

Multi_DB_Router/users/views.py
"""Views for login user."""
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views import View

from .forms import LoginForm, SignUpForm
from users.models import CustomUser


class LoginView(View):
    """Docstring for HomeView."""

    def get(self, request, *args, **kwargs):
        """To get Dashboard."""
        if not request.user.is_authenticated:
            return render(request, 'login.html', {'login': LoginForm()})
        return redirect('users:home')

    def post(self, request, *args, **kwargs):
        """To authenticate the user."""
        form = LoginForm(request.POST)
        user = authenticate(username=request.POST.get("email"), password=request.POST.get('password'))
        if user:
            login(request, user)
            return redirect('users:home')
        return render(request, 'login.html', {'login': form})


class HomeView(LoginRequiredMixin, View):
    """Docstring for HomeView."""

    def get(self, request, *args, **kwargs):
        """To get Dashboard."""
        ctx = {}
        if request.user.is_superuser:
            signup = SignUpForm()
            if kwargs.get('id'):
                user = CustomUser.objects.get(id=kwargs.get('id'))
                signup = SignUpForm(instance=user)
                ctx['id'] = kwargs.get('id')
            ctx['signup'] = signup
            ctx['user_list'] = CustomUser.objects.filter(is_staff=False)
            return render(request, 'users.html', ctx)
        else:
            return redirect('product:product')

    def post(self, request, *args, **kwargs):
        """To save the product."""
        user_list = CustomUser.objects.filter(is_staff=False)
        form = SignUpForm(request.POST)
        if kwargs.get('id'):
            user = CustomUser.objects.get(id=kwargs.get('id'))
            form = SignUpForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            if not kwargs.get('id'):
                user.set_password(request.POST.get("password"))
                send_mail(
                    'User created and Details About Login',
                    'Here are the Details regarging the Login to the website. Your Email is %s and your password is %s' %
                    (request.POST.get('email'), request.POST.get('password')),
                    'test@mailinator.com',
                    [request.POST.get('email')],
                    fail_silently=False,
                )
            user.save()
            messages.success(request, 'User successfully created.')
            return redirect('users:home')
        return render(request, 'users.html', {'user_list': user_list, 'signup': form, 'id': kwargs.get('id')})

Multi_DB_Router/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <title>MultiDB | {% block title %}Home{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-confirm.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom_style.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-confirm.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/aos.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
</head>
<body>
  {% block header %}
    {% include 'login_header.html' %}
  {% endblock %}
  {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'info' %}alert-warning{% else %} alert-danger{% endif %}">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <center><strong>{{ message }}!</strong></center>
    </div>
    {% endfor %}
  {% endif %}
  {% block content %}
  {% endblock  %}
  <footer>
    <div class="footer_sec"></div>
  </footer>
  <script type="text/javascript">
  </script>
  {%block script%}
  {% endblock  %}
</body>
</html>

Multi_DB_Router/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="signup-form">
    <form action="." method="post">
        {% csrf_token %}
		<h2>Login</h2>
		<p class="hint-text">Make yourself login</p>
        <div class="form-group">
        	{{login.email}}
        </div>
		<div class="form-group">
            {{login.password}}
        </div>
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
        </div>
    </form>
</div>
{% endblock %}

Multi_DB_Router/templates/login_header.html
<nav class="navbar navbar-default navbar-expand-xl navbar-light main_header">
  <div class="navbar-header d-flex col">
    <a class="navbar-brand" href="#"><i class="fa fa-cube"></i>Multiple<b>DB</b></a>     
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
    {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li class="nav-item active"><a href="{% url 'common-home' %}" class="nav-link"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
        {% if request.user.is_staff %}
          <li class="nav-item active"><a href="{% url 'product:product' %}" class="nav-link"><i class="fa fa-home" aria-hidden="true"></i> Product List</a></li>
        {% endif %}
        <li class="nav-item dropdown">
          <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle user-action"><i class="fa fa-user-circle"></i> {% if request.user.is_superuser %} Admin {% else %}{{request.user.first_name}} {{request.user.last_name}}{% endif %}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'logout' %}" class="dropdown-item"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
          </ul>
        </li>
      </ul>
    {% endif %}
  </div>
</nav>

Multi_DB_Router/templates/product.html
{% extends "base.html" %}
{% load common_helper %}
{% block title %}Product List{% endblock %}

{% block content %}
<div class="container">
	<div class="row home_section">
		<div class="col-md-5">
			<div class="listing_section">
				<div class="history_header">
					<h3>Add Product</h3>
				</div>
				<div class="history_container">
					<form action="{% if id %}{% url 'product:product_detail' id data %}{% else %}{% url 'product:product' %}{% endif %}" method="post">
					    {% csrf_token %}
					    {{ product }}
					    <div class="history_container">
					    	<button type="submit" class="btn btn-primary">Save</button>
					    </div>
					</form>
				</div>
			</div>
		</div>
		<div class="col-md-7">
			<div class="listing_section">
				<div class="history_header">
					<h3>List Of Products</h3>
				</div>
				<div class="row history_container">
					<table class="table table-striped">
					  <tr>
					  	<th scope="col">S.no.</th>
					  	{% if request.user.is_staff %}
					  	<th>User's Name</th>
					  	{% endif %}
					    <th scope="col">Database</th>
					    <th scope="col">Product Name</th>
					  </tr>
					  {% for database, name in product_list %}
						  <tr>
						  	<th scope="row">{{forloop.counter}}</th>
						  	{% if request.user.is_staff %}
						  	<td>{{name.user|get_user}}</td>
						  	{% endif %}
						    <td>{{database}}</td>
						    <td><a href="{% url 'product:product_detail' name.id database %}">{{name.product_name}}</a></td>
						  </tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Multi_DB_Router/templates/users.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}

{% block content %}
<div class="container">
	<div class="row home_section">
		<div class="col-md-4">
			<div class="listing_section">
				<div class="history_header">
					<h3>User Lists</h3>
				</div>
				<div class="history_container">
					<ul>
						{% if user_list %}
						    {% for users in user_list %}
						    <a class="users_details" href="{% url 'users:user_detail' users.id %}" data-id="{{users.id}}"><li class="users">{{users.first_name}}</li></a>
						    {% endfor %}
						{% else %}
							<li class="users">None</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="listing_section">
				<div class="history_header">
					<h3>Create User</h3>
				</div>
				<div class="history_container">
					<form action="{% if id %}{% url 'users:user_detail' id %}{% else %}{% url 'users:home' %}{% endif %}" method="post">
					    {% csrf_token %}
					    {{ signup }}
					    <div class="history_container">
					    	<button type="submit" class="btn btn-primary">Save</button>
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}